/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_panorama_NativePanorama */

#ifndef _Included_com_example_panorama_NativePanorama
#define _Included_com_example_panorama_NativePanorama
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_panorama_NativePanorama
 * Method:    processPanorama
 * Signature: ([JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_panorama_NativePanorama_processPanorama
  (JNIEnv *, jclass, jlongArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
